---

- name: install ppa openjdk repository
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'

- name: install java8
  apt: 
    name: openjdk-8-jre 
    state: present
    update_cache: yes

- name: install git
  apt:
    name: git
    state: present

- name: ensure .ssh directory exists.
  file: 
    dest: "/root/.ssh/"
    mode: 0700 
    owner: root
    state: directory

- name: install ssh key
  copy: 
    content: "{{ ssh_key }}" 
    dest: "{{ key_file }}"
    mode: 0600
    owner: root

- name: git clone calculator-service
  git:
    repo: git://foosball.example.org/path/to/repo.git
    dest: /root/

