---

- name: install ppa openjdk repository
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'

- name: install packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
       - openjdk-8-jdk
       - git
       - maven2    

- name: install git
  apt:
    name: git
    state: present

- name: ensure .ssh directory exists.
  file: 
    dest: "/root/.ssh/"
    mode: 0700 
    owner: root
    state: directory

- name: install ssh key
  copy: 
    content: "{{ ssh_key }}" 
    dest: "{{ key_file }}"
    mode: 0600
    owner: root

- name: git clone calculator-service
  git:
    repo: https://gitlab.com/devgrid/calculator-service.git
    dest: /root/calculator-service
    accept_hostkey: yes

- name: git clone calculator-service-test
  git:
    repo: https://gitlab.com/devgrid/calculator-service-test.git
    dest: /root/calculator-service-test
    accept_hostkey: yes