---

- name: add repo for java 8
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: accept java 8 oracle license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install java 8
  apt: name=oracle-java8-installer state=latest update-cache=yes force=yes

- name: install other packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
       - git
       - maven2
       - python-software-properties

- name: install git
  apt:
    name: git
    state: present

- name: ensure .ssh directory exists.
  file: 
    dest: "/root/.ssh/"
    mode: 0700 
    owner: root
    state: directory

- name: install ssh key
  copy: 
    content: "{{ ssh_key }}" 
    dest: "{{ key_file }}"
    mode: 0600
    owner: root

- name: git clone calculator-service
  git:
    repo: https://gitlab.com/devgrid/calculator-service.git
    dest: /root/calculator-service
    accept_hostkey: yes

- name: git clone calculator-service-test
  git:
    repo: https://gitlab.com/devgrid/calculator-service-test.git
    dest: /root/calculator-service-test
    accept_hostkey: yes